
app:
  cli-enabled: ${APP_CLI_ENABLED:true}

spring:
  application:
    name: user-service

  config:
    import:
      - "optional:configserver:"

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
      retry:
        max-attempts: 100
        initial-interval: 2000
        multiplier: 1.5
        max-interval: 20000



eureka:
  instance:
    hostname: user-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka