spring:
  application:
    name: discovery-server


  config:
    import:
      - "optional:configserver:http://config-server:8888"
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
      retry:
        max-attempts: 100
        initial-interval: 2000
        multiplier: 1.5
        max-interval: 20000
